apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/helm-repositories.yaml
  - cert-manager/cert-manager.yaml
  - cilium/cilium.yaml
  - external-secrets/external-secrets.yaml
  - external-dns/external-dns.yaml
  - longhorn/longhorn.yaml
  - vpa/vpa.yaml
  - victoria-metrics/victoria-metrics.yaml
  - opentelemetry/opentelemetry.yaml
  - kratix/kratix.yaml
