# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: audiobookshelf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: audiobooks-volume
              mountPath: /audiobooks
      volumes:
        - name: audiobooks-volume
          nfs:
            server: 192.168.2.184
            path: /volume1/media
---
# service
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf 
spec:
  selector:
    app: audiobookshelf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
# traeffik http route
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: audiobookshelf-route
  namespace: audiobookshelf
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
    #- name: cilium-gateway
    #  namespace: kube-system
  hostnames:
    - abs.lab.jake-watson.co.uk
  rules:
    - backendRefs:
        - name: audiobookshelf
          port: 80
---
# external dns
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: audiobookshelf-dns
  namespace: audiobookshelf
spec:
  endpoints:
    - dnsName: abs.lab.jake-watson.co.uk
      recordTTL: 180
      recordType: A
      targets:
        - 192.168.2.2