apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "http-ingress-visiblity"
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toEntities:
    - all
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "443"
        protocol: TCP
      - port: "8000"
        protocol: TCP
      - port: "8443"
        protocol: TCP
      - port: "53"
        protocol: ANY
      rules:
        http:
        - {}
  ingress:
  - fromEntities:
    - all
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "443"
        protocol: TCP
      - port: "8000"
        protocol: TCP
      - port: "8443"
        protocol: TCP
      rules:
        http:
        - {}