apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cilium
      reconciliationStrategy: "ChartVersion"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: '>1.15.4'
    repository: https://helm.cilium.io/
    name: cilium
  values:
    cgroup:
      autoMount:
        enabled: false
      hostRoot: "/sys/fs/cgroup"
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: 7445
    operator:
      enabled: true
      replicas: 1
      rollOutPods: true
      image:
        override: "quay.io/cilium/operator-generic-ci:e14988e02ce8d0f3451b177a4f97a3833df65ab3"

    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: false
    ipam:
      mode: "kubernetes"
    l2announcements:
      enabled: true
    image:
      override: "quay.io/cilium/cilium-ci:e14988e02ce8d0f3451b177a4f97a3833df65ab3"
    rollOutCiliumPods: true
    securityContext:
      capabilities:
        cleanCiliumState: "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
        ciliumAgent: "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
          
    gateway:
      enabled: true
