apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ui-hubble-route
  namespace: kube-system
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - hubble.lab.jake-watson.co.uk
  rules:
  - backendRefs:
      - name: hubble-ui
        port: 80