apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ui-hubble-route
  namespace: kube-system
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
    #- name: cilium-gateway
    #  namespace: kube-system
  hostnames:
    - hubble.lab.jake-watson.co.uk
  rules:
  - backendRefs:
      - name: hubble-ui
        port: 80
---
# external dns record
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: hubble-dns
  namespace: kube-system
spec:
  endpoints:
  - dnsName: hubble.lab.jake-watson.co.uk
    recordTTL: 180
    recordType: A
    targets:
    - 192.168.2.2