apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ui-route
  namespace: monitoring
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
    #- name: cilium-gateway
    #  namespace: kube-system
  hostnames:
    - grafana.lab.jake-watson.co.uk
  rules:
  - backendRefs:
      - name: kube-prometheus-grafana
        port: 80
---
# external dns record
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: grafana-dns
  namespace: monitoring
spec:
  endpoints:
  - dnsName: grafana.lab.jake-watson.co.uk
    recordTTL: 180
    recordType: A
    targets:
    - 192.168.2.2