apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ui-route
  namespace: monitoring
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
    #- name: cilium-gateway
    #  namespace: kube-system
  hostnames:
    - grafana.lab.jake-watson.co.uk
  rules:
  - backendRefs:
      - name: kube-prometheus-grafana
        port: 80