---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: default
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCVmuPwi7krM32M9BhQBL17HH6HZxkbALtcerRD2nxFDzpm5udnhddZvC2GzhVQ/MV25TrBre75xID1EkWY44ILYHy5aQU1vsprbC+bJYV+GSxxfQYb3VajsYgOdVjfI1stJ5bqhBR+8UMZ3OS/wa3gQpJ1+e95Fak+zfjzGunqg3hOScO0lrmpF0m4LoxvZ1EjxzkLb0CQcHlWpuZ30dq0ys3j2Ghi5Z/D3JknQDn7uCOax2bwCIN/aU3SS96TvBMKPgP0XjObX2Br7SD3k5qB1ziHw0f2BbpLF9Zs+T8VNI8p1xmYaUbE4AcrwO7apfiwNyH8LqkuWzLl5pqQpbCIp29BdNqGazSWUV86IrWLpqmo2pWszXGmJErOchvOIsNRZDhwohThOjTCEbffZ9KhUboxYoCyfTxPkKzAJUOsqCB6+8KxbWwn04aiAaxYi5KhQ915hbgn7C+gRdpxweuohb/ZjSrA+e74ECxk0Ns4D6uCtVtqoDQBZfXSy5EE9Fg3nfzoDTyVNz1YKL0rgw2U7IgIrNXiM9YC2JLLxhlXLzMd+N8TYBfGUE2pm23JQIlo1twZOfYqMT+zMm3sGzKfQTml2e1Ss1oSV7RT6KTjImr8EFCJc59LjBvZSY8D83c4H78ZEgZCNqVs1NOK+ae9+Lxt0oawEnFGySoEnQjFY7WMwPcuUi/+F7tsgRQbSbB2FLvARffWVw==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: default
