---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      version: ">=1.14.5"
  interval: 1m0s
  values:
    installCRDs: true
    prometheus:
      enabled: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
      - --dns01-recursive-nameservers-only=true
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
