apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatewayapi
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/my-cluster/gatewayapi/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-sources
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/my-cluster/helm-sources/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  dependsOn:
    - name: gatewayapi
      name: helm-sources
  interval: 10m0s
  path: ./clusters/my-cluster/cilium/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
  interval: 10m0s
  path: ./clusters/my-cluster/longhorn/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
  targetNamespace: sealed-secrets
  interval: 10m0s
  path: ./clusters/my-cluster/sealed-Secrets/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
    - name: sealed-secrets
  targetNamespace: external-dns
  interval: 10m0s
  path: ./clusters/my-cluster/external-DNS/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
  targetNamespace: cert-manager
  interval: 10m0s
  path: ./clusters/my-cluster/cert-manager/helm/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
    - name: cert-manager
    - name: external-dns
  targetNamespace: traefik
  interval: 10m0s
  path: ./clusters/my-cluster/traefik/helm/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  targetNamespace: audiobookshelf
  interval: 10m0s
  path: ./clusters/my-cluster/audiobookshelf/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
