apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-config
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
    - name: cert-manager
  interval: 10m0s
  path: ./clusters/my-cluster/external-DNS/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
