apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allowfromns-gateway
  namespace: cert-manager
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: traefik
  to:
  - group: ""
    kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      hostname: "*.lab.jake-watson.co.uk"
      protocol: HTTP
      port: 8443
      allowedRoutes:
        namespaces:
          from: All
      #tls:
      #  mode: Terminate
      #  certificateRefs:
      #    - name: jake-watson-co-uk-tls
      #      namespace: cert-manager
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway-exposed
  namespace: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: traefik
  listeners:
    - name: https
      hostname: "*.jake-watson.co.uk"
      protocol: HTTPS
      port: 8443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: jake-watson-co-uk
            namespace: cert-manager
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard-route
  namespace: traefik
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - traefik.lab.jake-watson.co.uk
  rules:
    - backendRefs:
        - name: traefik
          port: 9000
---
# external dns record
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: traefik-dns
  namespace: traefik
spec:
  endpoints:
    - dnsName: traefik.lab.jake-watson.co.uk
      recordTTL: 180
      recordType: A
      targets:
        - 192.168.2.2