apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: longhorn-repo
  namespace: longhorn-system
spec:
  interval: 5m0s
  url: https://github.com/longhorn/longhorn
  ref:
    branch: v1.6.x