---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart:  chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: longhorn-repo
  interval: 1m0s