apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ui-longhorn-route
  namespace: longhorn-system
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
    #- name: cilium-gateway
    #  namespace: kube-system
  hostnames:
    - longhorn.lab.jake-watson.co.uk
  rules:
  - backendRefs:
      - name: longhorn-frontend
        port: 80
---
# external dns record
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: longhorn-dns
  namespace: longhorn-system
spec:
  endpoints:
  - dnsName: longhorn.lab.jake-watson.co.uk
    recordTTL: 180
    recordType: A
    targets:
    - 192.168.2.2