apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ui-longhorn-route
  namespace: longhorn-system
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
    #- name: cilium-gateway
    #  namespace: kube-system
  hostnames:
    - longhorn.lab.jake-watson.co.uk
  rules:
  - backendRefs:
      - name: longhorn-frontend
        port: 80
