apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ui-route
  namespace: longhorn-system
spec:
  parentRefs:
    - name: traefik
      namespace: traefik-gateway
  hostnames:
    - longhorn.lab.jake-watson.co.uk
  rules:
  - backendRefs:
      - name: longhorn-frontend
        port: 80
